### ISSUE TITLE
The clip error

### ISSUE THREAD

**Issue by psuu0001** [gnobitab/FuseDream#11]
Hi, when I run command 'python fusedream_generator.py --text 'A photo of a blue dog.' --seed 1234' , there comes up an error. Why the clip library doesn't have "load" attribute? Does someone have same issue? My clip version is 0.2.0

Generating: A photo of a blue dog.
[8, 16, 32, 64, 128, 256, 512] {8: False, 16: False, 32: False, 64: True, 128: False, 256: False, 512: False}
Adding attention layer in G at resolution 64
Number of parameters: 82296804
Traceback (most recent call last):
  File "fusedream_generator.py", line 25, in <module>
    generator = FuseDreamBaseGenerator(G, config, 10) 
  File "/home/ubuntu/supy/FuseDream-main/fusedream_utils.py", line 150, in __init__
    self.clip_model, _ = clip.load(clip_mode, device=device) 
AttributeError: module 'clip' has no attribute 'load'

**Comment by ChengyueGongR** [comment]
I notice there is a similar issue together with the solution: [CLIP](https://github.com/openai/CLIP/issues/180). Not sure whether this is helpful or not.
